global_costmap:

  map_type: costmap
  track_unknown_space: true
  unknown_cost_value: 255
  obstacle_range: 10.0
  raytrace_range: 9.9
  inflation_radius: 0.5
  #transform_tolerance: 0.5
  robot_radius: 0.15
  inscribed_radius: 0.15
  circumscribed_radius: 0.15

  global_frame: /odom
  robot_base_frame: /base_link
  transform_tolerance: 0.5
  update_frequency: 5.0
  publish_frequency: 5.0
  static_map: true
  
  rolling_window: false
  #width: 80.0
  #height: 90.0
  resolution: 0.15

  #Investigate what this actually does
  cost_scaling_factor: 1.0
  
  #observation_sources: laser_scan_sensor

  #laser_scan_sensor: {sensor_frame: scan_front, data_type: LaserScan, topic: /vrep/scan_front, marking: true, clearing: true}
